### ISSUE TITLE
On the Effect of Squeeze and Excitation module

### ISSUE THREAD

**Issue by garyfanhku** [fabio-deep/Deep-Bayesian-Self-Training#1]
Thanks for releasing the source code! 
I found no mentioning of SE module in the paper and the corresponding codes commented out, am I correct to assume SE module weren't used in your experiments? 
And mind if I ask how did adding SE to densenet affect its performance? 

Many thanks

**Comment by fabio-deep** [comment]
No problem at all, thank you for the question. 

Yes you are correct the SE module wasn't used in the paper but it's something I was playing with a while back so I left it in there for anyone who might find it useful. 

As for the effects of SE on densenet, I have not studied them thoroughly so I can't say for sure. However based on a couple of experiments I think SE adds a lot of complexity using few extra parameters, so it might be a good idea for larger/more complex datasets.

Regards, 
Fabio

**Comment by garyfanhku** [comment]
Much appreciated for the clarification!
